google:
  maps:
    api_key: "AIzaSyAsrXACLOnFFX3mRkCxpscZDQ9b38CNMb0"

travel:
  api_url: "https://script.google.com/macros/s/AKfycbyI1AnSQcInkfz9MuX4JocClFAVHPdzWT-PAVKRwTvsgN3EPhw/exec"

stocks:
  api_url: "https://script.google.com/macros/s/AKfycbxzGCTgYDvkLGnUrbQpc7V1FxNojnNN3WBTcprX/exec"
  users: [ marina, valerij ]

