google:
  maps:
    api_key: "AIzaSyAsrXACLOnFFX3mRkCxpscZDQ9b38CNMb0"

travel:
  api_url: "https://script.google.com/macros/s/AKfycbwiTXVqYSdzt7MCiR4hAfrf1-o96HOhAEnv_dWGx4k/dev"

stocks:
  api_url: "https://script.google.com/macros/s/AKfycbxzGCTgYDvkLGnUrbQpc7V1FxNojnNN3WBTcprX/exec"
  users: [ marina, valerij ]

